#! /usr/bin/env bash

set -u -e -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

libs=('crunch' 'cgltf')

crunch_prefix='https://raw.githubusercontent.com/DaemonEngine/crunch/refs/heads/master/inc/'
crunch_files=('crn_decomp.h' 'crn_defs.h' 'crnlib.h')

cgltf_prefix='https://raw.githubusercontent.com/jkuhlmann/cgltf/refs/heads/master/'
cgltf_files=('cgltf.h' 'cgltf_write.h')

for lib in "${libs[@]}"
do
	libdir="libs/${lib}"
	mkdir -p "${libdir}"
	cd "${libdir}"

	prefix="$(eval "echo \"\${${lib}_prefix}\"")"
	files=($(eval "echo \"\${${lib}_files[@]}\""))

	for file in "${files[@]}"
	do
		url="${prefix}${file}"
		wget -O "${file}" "${url}"
		dos2unix "${file}"
	done
done
