if (YOKAI_TARGET_SYSTEM_WINDOWS)
    set(BUNDLE_SHARE ON)
elseif (YOKAI_TARGET_SYSTEM_MACOS)
    set(BUNDLE_SHARE ON)
    set(BUNDLE_ETC ON)
elseif (YOKAI_TARGET_SYSTEM_LINUX)
elseif (YOKAI_TARGET_SYSTEM_FREEBSD)
else ()
    set(BUNDLE_OS_NAME "unsupported")
endif ()

STRING(TOLOWER "${YOKAI_TARGET_SYSTEM_NAME}" BUNDLE_OS_NAME)

add_custom_target(bundle ALL
    COMMAND
    export LD_LIBRARY_PATH=$ENV{LD_LIBRARY_PATH} &&
    "${PROJECT_SOURCE_DIR}/library-bundler"
    "${BUNDLE_OS_NAME}" "${PROJECT_BINARY_DIR}"
    VERBATIM
    COMMENT "Bundling libraries"
)

install(DIRECTORY
    ${PROJECT_BINARY_DIR}/lib
    DESTINATION ${FINAL_INSTALL_PREFIX}
)

if (BUNDLE_SHARE)
    install(DIRECTORY
        ${PROJECT_BINARY_DIR}/share
        DESTINATION ${FINAL_INSTALL_PREFIX}
    )
endif ()

if (BUNDLE_ETC)
    install(DIRECTORY
        ${PROJECT_BINARY_DIR}/etc
        DESTINATION ${FINAL_INSTALL_PREFIX}
    )
endif ()
